## Exercise 7: NaN

In [6]:
import numpy as np

generator = np.random.default_rng(123)
print(generator)
print("\n")
grades = np.round(generator.uniform(low=0.0, high=10.0, size=(10, 2)))
print(grades)
print("\n")
grades[[1, 2, 5, 7], [0, 0, 0, 0]] = np.nan
print(grades)


Generator(PCG64)


[[7. 1.]
 [2. 2.]
 [2. 8.]
 [9. 3.]
 [8. 9.]
 [5. 2.]
 [8. 2.]
 [7. 6.]
 [9. 2.]
 [8. 5.]]


[[ 7.  1.]
 [nan  2.]
 [nan  8.]
 [ 9.  3.]
 [ 8.  9.]
 [nan  2.]
 [ 8.  2.]
 [nan  6.]
 [ 9.  2.]
 [ 8.  5.]]


In [7]:
third_col = np.where(np.isnan(grades[:, 0]), grades[:, 1], grades[:, 0])
print(third_col)

[7. 2. 8. 9. 8. 2. 8. 6. 9. 8.]


In [8]:
result = np.column_stack((grades, third_col))
print(result)


[[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [nan  2.  2.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [ 8.  5.  8.]]
