## Exercise 5: Split, concatenate, reshape arrays

In [1]:
import numpy as np
# 1. Generate an array with integers from 1 to 50
arr1 = np.arange(1, 51)
print("Array 1 (1–50):\n", arr1, "\n")

Array 1 (1–50):
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50] 



In [2]:
# 1. Generate an array with integers from 51 to 100
arr2 = np.arange(51, 101)
print("Array 2 (51-100):\n", arr2, "\n")

Array 2 (51-100):
 [ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100] 



In [5]:
# 3. Concatenate the two arrays
arr_concat = np.concatenate((arr1, arr2))
print("Concatenated Array (1-100)\n", arr_concat)

Concatenated Array (1-100)
 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [8]:
# 4. Reshape into 10x10
arr_reshaped = arr_concat.reshape(10,10)
print("Reshaped 10x10 Array:\n", arr_reshaped)

Reshaped 10x10 Array:
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
