## Exercise 6: Broadcasting and Slicing


In [2]:
import numpy as np

# Step 1
arr = np.ones((9, 9), dtype=np.int8)
print(arr)

[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]


In [30]:
# Copy so we don't overwrite arr
maze = arr.copy()
print(maze)

int8


In [29]:
# Set inside (rows 1:-1, cols 1:-1) to 0
maze[1:-1, 1:-1] = 0
maze[2:-2, 2:-2] = 1
maze[3:-3, 3:-3] = 0
maze[4:-4, 4:-4] = 1
print(maze)

[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]


In [39]:
array_1 = np.array([1, 2, 3, 4, 5], dtype=np.int8)   # shape (5,)
array_2 = np.array([1, 2, 3], dtype=np.int8)        # shape (3,)

print(array_1, array_1.shape)
print("\n")
print(array_2, array_2.shape)


[1 2 3 4 5] (5,)


[1 2 3] (3,)


In [38]:
array_2 = array_2[:, np.newaxis]   # shape becomes (3,1)

print(array_1, array_1.shape)
print("\n")
print(array_2, array_2.shape)

[1 2 3 4 5] (5,)


[[[1]]

 [[2]]

 [[3]]] (3, 1, 1)


In [37]:
result = array_2 * array_1
print(result)


[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]]
